<?php
// This class (a User Model) is used to store the users in the `chat_application_users` in the database table



class ChatUserModel
{
	// `chat_application_users` database table column names
	private $user_id;
	private $user_name;
	private $user_email;
	private $user_password;
	private $user_profile;
	private $user_status;
	private $user_created_on;
	private $user_verification_code; // Registration Verification Code sent to the user's email
	private $user_login_status;
	private $showemail;
	private $user_token; // A random unique string we generate with every login to be used in conjunction with `user_connection_id` to implement One-to-One Private Chat
	private $user_connection_id; // The unique connection ID generated by WebSocket for every connected client (used in conjuntion with `user_token` column to implement One-to-One Private Chat)
	public $connect;



	public function __construct()
	{
		// Establish the database connection
		require_once('Database_connection.php');
		$database_object = new Database_connection;
		$this->connect = $database_object->connect();
	}


	// Setters and Getters
	function setUserId($user_id)
	{
		$this->user_id = $user_id;
	}

	function getUserId()
	{
		return $this->user_id;
	}

	function setUserName($user_name)
	{
		$this->user_name = $user_name;
	}

	function getUserName()
	{
		return $this->user_name;
	}

	function setUserEmail($user_email)
	{
		$this->user_email = $user_email;
	}

	function getUserEmail()
	{
		return $this->user_email;
	}

	function setUserPassword($user_password)
	{
		$this->user_password = $user_password;
	}

	function getUserPassword()
	{
		return $this->user_password;
	}

	function setUserProfile($user_profile)
	{
		$this->user_profile = $user_profile;
	}

	function getUserProfile()
	{
		return $this->user_profile;
	}

	function setUserStatus($user_status)
	{
		$this->user_status = $user_status;
	}

	function getUserStatus()
	{
		return $this->user_status;
	}

	function setUserCreatedOn($user_created_on)
	{
		$this->user_created_on = $user_created_on;
	}

	function getUserCreatedOn()
	{
		return $this->user_created_on;
	}

	function setUserVerificationCode($user_verification_code)
	{
		$this->user_verification_code = $user_verification_code;
	}

	function getUserVerificationCode()
	{
		return $this->user_verification_code;
	}

	function setUserLoginStatus($user_login_status)
	{
		$this->user_login_status = $user_login_status;
	}

	function getUserLoginStatus()
	{
		return $this->user_login_status;
	}

	function setUserToken($user_token)
	{
		$this->user_token = $user_token;
	}

	function getUserToken()
	{
		return $this->user_token;
	}

	function setUserConnectionId($user_connection_id)
	{
		$this->user_connection_id = $user_connection_id;
	}

	function getUserConnectionId()
	{
		return $this->user_connection_id;
	}

	function make_avatar($character)
	{
	    $path = "images/". time() . ".png";
		$image = imagecreate(200, 200);
		$red = rand(0, 255);
		$green = rand(0, 255);
		$blue = rand(0, 255);
	    imagecolorallocate($image, $red, $green, $blue);  
	    $textcolor = imagecolorallocate($image, 255,255,255);

	    $font = dirname(__FILE__) . '/font/arial.ttf';

	    imagettftext($image, 100, 0, 55, 150, $textcolor, $font, $character);
	    imagepng($image, $path);
	    imagedestroy($image);
	    return $path;
	}

	function get_user_data_by_email()
	{
		$query = 
			"SELECT * FROM chat_application_users 
			WHERE user_email = :user_email"
		;

		$statement = $this->connect->prepare($query);

		$statement->bindParam(':user_email', $this->user_email);

		if ($statement->execute())
		{
			$user_data = $statement->fetch(PDO::FETCH_ASSOC);
		}

		return $user_data;
	}

	function save_data()
	{
		$query =
			"INSERT INTO chat_application_users (user_name, user_email, user_password, user_profile, user_status, user_created_on, user_verification_code) 
			VALUES (:user_name, :user_email, :user_password, :user_profile, :user_status, :user_created_on, :user_verification_code)"
		;
		$statement = $this->connect->prepare($query);

		$statement->bindParam(':user_name'			   , $this->user_name);
		$statement->bindParam(':user_email'			   , $this->user_email);
		$statement->bindParam(':user_password'		   , $this->user_password);
		$statement->bindParam(':user_profile'		   , $this->user_profile);
		$statement->bindParam(':user_status'		   , $this->user_status);
		$statement->bindParam(':user_created_on'       , $this->user_created_on);
		$statement->bindParam(':user_verification_code', $this->user_verification_code);

		if ($statement->execute())
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	function is_valid_email_verification_code()
	{
		$query = 
			"SELECT * FROM chat_application_users 
			WHERE user_verification_code = :user_verification_code"
		;

		$statement = $this->connect->prepare($query);

		$statement->bindParam(':user_verification_code', $this->user_verification_code);

		$statement->execute();

		if ($statement->rowCount() > 0)
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	function enable_user_account()
	{
		$query = 
			"UPDATE chat_application_users
			SET user_status = :user_status
			WHERE user_verification_code = :user_verification_code"
		;

		$statement = $this->connect->prepare($query);

		$statement->bindParam(':user_status'		   , $this->user_status);
		$statement->bindParam(':user_verification_code', $this->user_verification_code);

		if ($statement->execute())
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	function update_user_login_data()
	{
		$query =
			"UPDATE chat_application_users 
			SET
				user_login_status = :user_login_status,
				user_token 		  = :user_token  
			WHERE
				user_id = :user_id"
		;

		$statement = $this->connect->prepare($query);

		$statement->bindParam(':user_login_status', $this->user_login_status);
		$statement->bindParam(':user_token'		  , $this->user_token);
		$statement->bindParam(':user_id'		  , $this->user_id);

		if ($statement->execute())
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	function get_user_data_by_id()
	{
		$query = 
			"SELECT * FROM chat_application_users 
			WHERE user_id = :user_id"
		;

		$statement = $this->connect->prepare($query);
		$statement->bindParam(':user_id', $this->user_id);

		try
		{
			if ($statement->execute())
			{
				$user_data = $statement->fetch(PDO::FETCH_ASSOC);
			}
			else
			{
				$user_data = array();
			}
		}
		catch (Exception $error)
		{
			echo $error->getMessage();
		}


		return $user_data;
	}

	function upload_image($user_profile)
	{
		$extension = explode('.', $user_profile['name']);
		$new_name = rand() . '.' . $extension[1];
		$destination = 'images/' . $new_name;
		move_uploaded_file($user_profile['tmp_name'], $destination);
		return $destination;
	}

	function update_data()
	{
		$query =
			"UPDATE chat_application_users 
			SET
				user_name     = :user_name,
				showemail	  = :showemail,
				user_email    = :user_email, 
				user_password = :user_password, 
				user_profile  = :user_profile  
			WHERE user_id = :user_id"
		;

		$statement = $this->connect->prepare($query);

		$statement->bindParam(':user_name'	  , $this->user_name);
		$statement->bindParam(':user_email'   , $this->user_email);
		$statement->bindParam(':user_password', $this->user_password);
		$statement->bindParam(':user_profile' , $this->user_profile);
		$statement->bindParam(':user_id'	  , $this->user_id);
		$statement->bindParam(':showemail'	  , $this->showemail);

		if ($statement->execute())
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	function get_user_all_data()
	{
		$query =
			"SELECT * FROM chat_application_users "
		;

		$statement = $this->connect->prepare($query);
		$statement->execute();
		$data = $statement->fetchAll(PDO::FETCH_ASSOC);

		return $data;
	}

	function get_user_all_data_with_status_count() // This method gets every single (i.e. all users) user's data in `chat_application_users` table and the count of 'Unread' Messages that they (he/she) sent to the authenticated/logged-in user
	{
		// Query Explanation: For EVERY user in the `chat_application_users` table, select `user_id`, `user_name`, `user_profile`, `user_login_status`, and the count/number of the 'Unread' Messages that they (he/she) sent to the authenticated/logged-in user (by using a Nested Query/Subquery that selects the messages that are sent from every user to the authenticated/logged-in user, and this message is 'Unread' i.e. `status` = 'No'. To further clarify this, here is an example: Select the data of 'Kassem' from `chat_application_users` table and the count of the 'Unread' Messages that he sent to the authenticated/logged-in user)
		$query =
			"SELECT
				user_id,
				user_name,
				user_profile,
				user_login_status,
				user_email,
				showemail,
				(SELECT COUNT(*) FROM private_chat_messages
					WHERE
						from_user_id = chat_application_users.user_id
					AND
						status = 'No'
				) AS count_status
			FROM chat_application_users"
		;

		$statement = $this->connect->prepare($query);
		//$statement->bindParam(':user_id', $this->user_id);
		$statement->execute();
		$data = $statement->fetchAll(PDO::FETCH_ASSOC);

		return $data;
	}

	function update_user_connection_id()
	{
		$query =
			"UPDATE chat_application_users 
			SET user_connection_id = :user_connection_id 
			WHERE user_token = :user_token"
		;

		$statement = $this->connect->prepare($query);

		$statement->bindParam(':user_connection_id', $this->user_connection_id);
		$statement->bindParam(':user_token'		   , $this->user_token);

		$statement->execute();
	}

	function get_user_id_from_token()
	{
		$query =
			"SELECT user_id FROM chat_application_users 
			WHERE user_token = :user_token"
		;

		$statement = $this->connect->prepare($query);
		$statement->bindParam(':user_token', $this->user_token);
		$statement->execute();
		$user_id = $statement->fetch(PDO::FETCH_ASSOC);

		return $user_id;
	}
	
	public function addUserToGC( $userid, $chatid ) {
		$query =
			"SELECT * FROM chat_application_users 
			WHERE user_id = :user_id"
		;

		$statement = $this->connect->prepare( $query );
		$statement->bindParam(':user_id', $userid);
		$statement->execute();
		$member = $statement->fetch(PDO::FETCH_ASSOC)["memberof"];
		
		if( isset($member) && !empty($member) && strlen($member) > 0 ) {
			$mlist = explode( ",", $member );
			for( $i = 0; $i < count($mlist); $i++ ) {
				if( $mlist[$i] == $chatid ) return 0;
			}
			unset( $mlist );
		}

		if( isset($member) && !empty($member) && strlen($member) > 0 ) {
			$member .= ",".$chatid;
		} else $member = $chatid;
		
		$query =
			"UPDATE chat_application_users SET memberof = :memberof WHERE user_id = :userid"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':userid', $userid );
		$statement->bindParam( ':memberof', $member );
		$statement->execute();

		return 1;
	}

	function newGroup( $name, $userid ) {
		$query =
			"INSERT INTO group_chats( chatname ) VALUES( :chatname )"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':chatname', $name );
		$statement->execute();
		$id = $this->connect->lastInsertId();
		
		$this->addUserToGC( $userid, $id );

		return $id;
	}
	
	function getMyGroups( $ids ) {
		$res = array();
		$res_ = array();
		
		for( $i = 0; $i < count($ids); $i++ ) {
			$query =
				"SELECT * FROM group_chats WHERE id=:groupid"
			;

			$statement = $this->connect->prepare( $query );
			$statement->bindParam( ':groupid', $ids[$i] );
			$statement->execute();

			$res_ = $statement->fetchAll( PDO::FETCH_ASSOC );
			if( count($res_) > 0 ) $res[] = $res_;
		}
		
		return $res;
	}
	
	function getGroupById( $id ) {
		$query =
			"SELECT * FROM group_chats WHERE id=:groupid"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':groupid', $id );
		$statement->execute();

		return $statement->fetchAll( PDO::FETCH_ASSOC );
	}

	function getGroupMessages( $id ) {
		$query =
			"SELECT * FROM group_chat_messages WHERE groupid=:groupid"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':groupid', $id );
		$statement->execute();
		
		return $statement->fetchAll( PDO::FETCH_ASSOC );
	}
	
	public function getUsernameById( $id ) {
		$query =
			"SELECT user_name FROM chat_application_users WHERE user_id=:user_id"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':user_id', $id );
		$statement->execute();
		
		return $statement->fetchAll( PDO::FETCH_ASSOC )[0]["user_name"];
	}
	
	public function removeMessage( $msgid ) {
		$query =
			"DELETE FROM group_chat_messages WHERE id=:msgid"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':msgid', $msgid );
		$statement->execute();
	}

	public function setShowemail( $s ) {
		$this->showemail = $s;
	}

	public function sendChatMessage( $userid, $msg, $grpid ) {
		$query =
			"INSERT INTO group_chat_messages( userid, group_chat_message, groupid ) VALUES( :userid, :group_chat_message, :groupid )"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':userid', $name );
		$statement->bindParam( ':group_chat_message', $msg );
		$statement->bindParam( ':groupid', $grpid );
		$statement->execute();
	}

	public function updateMessage( $msgid, $msg ) {
		$query =
			"UPDATE group_chat_messages SET group_chat_message=:msg WHERE id=:msgid"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':msgid', $msgid );
		$statement->bindParam( ':msg', $msg );
		$statement->execute();
	}

	public function updatePMessage( $msgid, $msg ) {
		$query =
			"UPDATE private_chat_messages SET private_chat_message=:msg WHERE chat_message_id=:msgid"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':msgid', $msgid );
		$statement->bindParam( ':msg', $msg );
		$statement->execute();
	}

	public function removePMessage( $msgid ) {
		$query =
			"DELETE FROM private_chat_messages WHERE chat_message_id=:msgid"
		;
		
		$statement = $this->connect->prepare( $query );
		$statement->bindParam( ':msgid', $msgid );
		$statement->execute();
	}
}

?>